import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import StoreProvider from '@/store/StoreProvider';
import { clsx } from 'clsx';
import Header from '@/components/Header/Header';
import SWRConfigContext from '@/context/SWRConfigContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body
        className={clsx(
          inter.className,
          'bg-slate-100',
          'w-full',
          'm-auto',
          'max-w-screen-sm',
          'shadow',
        )}
      >
        <SWRConfigContext>
          <StoreProvider>
            <Header />
            {children}
          </StoreProvider>
        </SWRConfigContext>
      </body>
    </html>
  );
}
